# Podfile
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target 'locator' do

pod 'Alamofire', '~> 3.0'
pod 'GoogleMaps'
pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
pod 'PromiseKit', '~> 3.0'
pod 'FBSDKCoreKit', '4.10.0'
pod 'FBSDKLoginKit', '4.10.0'
pod 'FBSDKShareKit', '4.10.0'
pod 'HanekeSwift'
pod 'Fusuma'
pod 'Mixpanel'
pod 'PageMenu'
pod 'BWWalkthrough'

end
