# Podfile
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target 'locator' do

pod 'Alamofire', '~> 3.0'
pod 'GoogleMaps'
pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
pod 'PromiseKit', '~> 3.0'
pod 'FBSDKCoreKit', '4.9.0-beta2'
pod 'FBSDKLoginKit', '4.9.0-beta2'
pod 'FBSDKShareKit', '4.9.0-beta2'
pod 'HanekeSwift'
pod 'SlackTextViewController', '1.9.1'

end
