language: objective-c
xcode_project: locator/locator.xcodeproj
#xcode_workspace: locator/locator.xcworkspace
xcode_scheme: locator
podfile: locator/Podfile
osx_image: xcode7.3
xcode_sdk: iphonesimulator9.3 

rvm:  
  - 2.2.2
before_install: 
  - gem install cocoapods