language: objective-c
#xcode_project: locator/locator.xcodeproj
xcode_workspace: locator/locator.xcworkspace
xcode_scheme: locator
podfile: locator/Podfile
osx_image: xcode7.3
xcode_sdk: iphonesimulator9.3 
rvm:  
  - 2.2.2
before_install: 
  - git clone https://github.com/facebook/xctool.git
  - gem install cocoapods
  - cd locator && pod install

script:
  - xctool/xctoolsh -workspace locator/locator.xcworkspace -scheme locator -sdk iphonesimulator9.3 build test
  - xctool/xctoolsh -workspace locator/locator.xcworkspace -scheme locator -sdk macosx.3 build test